### ISSUE TITLE
Should we depend on composer-envato

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/composer-theme-fusion#2]
Could this plugin be used *without* composer-envato?

@dlecan ?

**Comment by szepeviktor** [comment]
yes -> `"require"`
no -> `"suggest"`

**Comment by dlecan** [comment]
Fusions plugins are sold with Avada theme, so, I would suggest "require".
My 2 cents :wink:

**Comment by szepeviktor** [comment]
Thank you @dlecan !

2:0 to "require".
